language: julia
notifications:
  email: false
julia:
  - 0.4
  #- nightly  # Nemo.jl fails for nightly
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.init(); Pkg.clone(pwd()); Pkg.test("AlgebraicNumbers")'
