language: julia
sudo: false
os:
  - linux 
  - osx
notifications:
  email: false
julia:
  - 1.0
  #- nightly
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'using Pkg; Pkg.test(coverage=true)'
after_success:
  - cat Manifest.toml
  - julia --color=yes -e 'using Coverage; Coveralls.submit(Coveralls.process_folder())'