language: julia
notifications:
  email: false
julia:
  - 1.0
  - nightly
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'using Pkg; Pkg.init(); Pkg.clone(pwd()); Pkg.test("AlgebraicNumbers"; coverage=true)'
after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("AlgebraicNumbers")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
